[project]
name = "dhybridrpy"
version = "v1.12"
description = "A Python package to easily read input + output data from dHybridR."
readme = "README.md"
requires-python = ">=3.8"
license = "AGPL-3.0-only"
license-files = ["LICENSE"]
dependencies = [
    "h5py",
    "matplotlib",
    "numpy",
    "ruff",
    "f90nml",
    "pre-commit",
    "dask",
    "typer>=0.20.1",
    "joblib>=1.4.2",
]

[project.urls]
Homepage = "https://github.com/AstroplasmasUChicago/dhybridrpy"

[project.scripts]
dplot = "dhybridrpy.__main__:main"

[build-system]
requires = ["setuptools>=77", "wheel"]
build-backend = "setuptools.build_meta"
